version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    image: my-livewire-crud-app
    container_name: laravel_app
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      
    working_dir: /var/www/html
    user: "www-data"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: livewire_crud_app
      MYSQL_USER: livewire_crud_app
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
